### ISSUE TITLE
Handle TransferComplete call

### ISSUE THREAD

**Issue by pftbest** [Fullrate/acs_ex#2]
Sorry if it's a stupid question, but how can I handle TransferComplete call?

`session_start` only gives me an inform data, but I would like to know if CPE sent a
TransferComplete after the Inform.

I see on the network that ACS correctly responds with `cwmp:TransferCompleteResponse` and that is great, I just don't see how can I get the data from it.

**Comment by dalegaard** [comment]
Hi!

It's not super well documented, so I don't think this one is on you ;-)

You can use the ` ACS.Session.Script.Vendor.Helpers.session_messages/1` function to grab all messages that weren't the result of another API call that you sent yourself. You should look for the `7 TRANSFER COMPLETE` event in the inform, and then call `session_messages/`. The `TransferComplete` won't arrive until the `InformResponse` has been returned to the CPE, so `session_messages/1` will block waiting for any messages.

Does that fix your issue?

Best regards, Lasse

**Comment by pftbest** [comment]
Hello, this is very helpful, thank you. I'll try this call when I get some time.

**Comment by pftbest** [comment]
I just tried this call and it works perfectly, thank you!
