### ISSUE TITLE
Empty session cookie = no session cookie?

### ISSUE THREAD

**Issue by rtATvw** [Fullrate/acs_ex#5]
Either an empty session cookie is supposed to be ignored, someone (Grandstream) doesn't follow the specification, or the specifications differ between versions.

 acs_ex/lib/handlers/acs.ex:
Line 25:
-      Map.has_key?(cookies,"session") != "" ->
+     Map.has_key?(cookies,"session") && cookies["session"] != "" ->

**Comment by rtATvw** [comment]
As an alternative send a response to the client to delete the session cookie when ending the session.
If the session cookie is removed from the server then it should be removed from the client as well.

acs_ex/lib/handlers/acs.ex:
Line 100:
```
    if resp == "", do: ACS.Session.Supervisor.end_session(session_id)

    conn
    |> put_resp_content_type("text/xml")
    |> put_resp_cookie("session", session_id)
    |> send_resp(code, resp)

```

to:

```
    cond do
      resp == "" ->
        ACS.Session.Supervisor.end_session(session_id)
        conn
          |> put_resp_content_type("text/xml")
          |> put_resp_cookie("session", "", max_age: 0)
          |> send_resp(code,resp)
      true ->
        conn
          |> put_resp_content_type("text/xml")
          |> put_resp_cookie("session", session_id)
          |> send_resp(code,resp)
    end
```

**Comment by jdalberg** [comment]
I'll have a look. Haven't looked at this thing in forever, so perhaps other things need seeing to :)
